// ---------------------------------------------------------------------------
// roster — write ROSTER.md out of the live balance table.
//
// This exists rather than a hand-written document because a hand-written one
// would be a second copy of every number in STAT_DEFS, which is the one thing
// this codebase is strict about: the library edits those values while a round
// runs and a duplicate does not follow. A roster that goes stale the first time
// somebody tunes a tower is worse than no roster, so this reads the numbers the
// game actually resolves and regenerates the file.
//
// The prose comes from the assets' own `note` fields, which were already
// written to explain what each thing is for.
//
//   node tools/roster.mjs            # rewrites ROSTER.md
//   node tools/roster.mjs --print    # to stdout instead
// ---------------------------------------------------------------------------
import { open, ROOT } from './harness.mjs';
import fs from 'node:fs';
import path from 'node:path';

const { page, close } = await open();

const R = await page.evaluate(() => {
  __nw.start(4242);                       // syncs names out of the text table
  const G = __hf.game;
  const note = id => { try { const m = HF.assetMeta(id); return (m && m.note) || ''; }
                       catch (e) { return ''; } };
  const out = { cats: G.CATS.map(c => ({ id: c.id, name: c.name })),
                types: [], units: [], enemy: [], world: [], diff: G.DIFF,
                ehp: {}, nest: HF.statsOf('nest') || {}, salvage: HF.statsOf('salvage') || {} };
  for (const t in G.TYPES) {
    const T = G.TYPES[t];
    out.types.push({ id: t, name: T.name, cat: T.cat, foot: T.foot | 0,
                     road: !!T.road, s: HF.statsOf(t) || {}, note: note(t) });
  }
  for (const u in G.UNITS) {
    const U = G.UNITS[u];
    out.units.push({ id: u, name: U.name, civil: !!U.civil, melee: !!U.melee,
                     s: HF.statsOf(u) || {}, note: note(u) });
  }
  // The horde's ids and its asset ids differ: the shambler is drawn from the
  // "swarm" asset, and the base stat line lives under that name too.
  const ASSET = { shambler: 'swarm', runner: 'runner', brute: 'brute' };
  for (const e in G.ENEMY) {
    const E = G.ENEMY[e];
    out.enemy.push({ id: e, name: E.name, s: HF.statsOf(ASSET[e] || e) || {},
                     note: note(ASSET[e] || e) });
  }
  out.world.push({ id: 'nest', name: 'Nest', s: out.nest, note: note('nest') });
  out.world.push({ id: 'salvage', name: 'Salvage Pile', s: out.salvage, note: note('salvage') });
  for (const d in G.DIFF) out.ehp[d] = G.DIFF[d].hp;
  return out;
});
await close();

// ---- formatting ------------------------------------------------------------
const n = (v, d = 2) => v === undefined ? '—'
  : (Math.round(v * 10 ** d) / 10 ** d).toString();
const dps = (dmg, every) => (dmg && every) ? n(dmg / every, 1) : '—';
const L = [];
const push = (...s) => L.push(...s);

push('# Nightward — roster', '',
     '*Generated by `node tools/roster.mjs` from the live balance table. Do not',
     'hand-edit: every number here comes from `STAT_DEFS` in `src/d_core.js`, and',
     'a second copy would stop following the values the in-game library edits.*', '');

// ---- friendly --------------------------------------------------------------
push('---', '', '## Yours', '');

push('### Units', '');
push('| | health | speed | damage | dps | reach / range | leash | also |',
     '|---|---|---|---|---|---|---|---|');
const order = ['commander', 'soldier', 'archer', 'worker'];
const us = R.units.slice().sort((a, b) => order.indexOf(a.id) - order.indexOf(b.id));
for (const u of us) {
  const s = u.s, every = u.melee ? s.swing : s.fire, also = [];
  if (s.gather !== undefined)
    also.push(`gathers ${n(s.gather)}/s · carries ${s.carry} · repairs ${s.repair} hp/s`);
  if (s.rally !== undefined)
    also.push(`rallies within ${n(s.rally)}, cutting their swing to ${Math.round(s.rallyK * 100)}%`);
  push(`| **${u.name}** | ${n(s.hp, 0)} | ${n(s.speed)} | ` +
       (s.dmg ? `${s.dmg} / ${n(every)}s` : '—') + ` | ${dps(s.dmg, every)} | ` +
       `${n(u.melee ? s.reach : s.range)} | ${n(s.leash)} | ${also.join('; ') || '—'} |`);
}
push('');
// The notes carry the prose and usually quote their own numbers, so nothing
// derived is repeated underneath them — a table row followed by the same
// figures in a lowercase fragment was the first draft and it read like a leak.
for (const u of us) if (u.note) push(`**${u.name}.** ${u.note}`, '');

push('### Structures', '');
for (const c of R.cats) {
  const inCat = R.types.filter(t => t.cat === c.id);
  if (!inCat.length) continue;
  push(`#### ${c.name}`, '');
  push('| | supply | health | goes up in | path cost | footprint | what it does |',
       '|---|---|---|---|---|---|---|');
  for (const t of inCat) {
    const s = t.s, bits = [];
    if (s.dmg !== undefined)
      bits.push(`${s.dmg} every ${n(s.fire)}s to ${n(s.range)} (${dps(s.dmg, s.fire)} dps)`);
    if (s.splash !== undefined)
      bits.push(`splash ${Math.round(s.splashK * 100)}% across ${n(s.splash)}`);
    if (s.aura !== undefined)
      bits.push(`guns within ${n(s.aura)} reload ${Math.round((1 - s.auraK) * 100)}% faster`);
    if (s.cap !== undefined)
      bits.push(`houses ${s.cap}, replaced every ${n(s.retrain)}s`);
    if (t.road)
      bits.push(`+${Math.round(s.speed * 100)}% speed within ${n(s.width)}, ` +
                `runs of ${s.minLen}–${s.maxLen}, ends snap within ${n(s.snap)}`);
    push(`| **${t.name}** | ${t.road ? '—' : (s.cost === undefined ? 'free' : s.cost)} | ` +
         `${s.hp === undefined ? '—' : n(s.hp, 0)} | ` +
         `${t.road ? n(s.build) + 's per unit' : n(s.raise) + 's'} | ` +
         `${s.pathCost === undefined ? '—' : s.pathCost} | ` +
         `${t.road ? 'off-grid' : t.foot + '×' + t.foot} | ${bits.join('; ') || '—'} |`);
  }
  push('');
  for (const t of inCat) if (t.note) push(`**${t.name}.** ${t.note}`, '');
}

// ---- enemy -----------------------------------------------------------------
push('---', '', '## Theirs', '');
push('Attacker health is a multiplier on the round\'s base, which is set by',
     'difficulty and rises ' + n((R.nest.ehpK - 1) * 100, 0) + '% each night. Night one:', '');
push('| | health × | ' + Object.keys(R.diff).map(d => R.diff[d].label + ' n1').join(' | ') +
     ' | speed | vs buildings | vs the hall | reach |',
     '|---|---|' + Object.keys(R.diff).map(() => '---|').join('') + '---|---|---|---|');
for (const e of R.enemy) {
  const s = e.s;
  push(`| **${e.name}** | ${n(s.hpK)} | ` +
       Object.keys(R.diff).map(d => n(R.ehp[d] * s.hpK, 0)).join(' | ') +
       ` | ${n(s.speed)} | ${s.dmgBuild} | ${s.dmgHall} | ${n(s.reach)} |`);
}
push('');
for (const e of R.enemy) if (e.note) push(`**${e.name}.** ${e.note}`, '');

push('### Where they come from', '');
const N = R.nest, S = R.salvage;
const world = id => R.world.find(w => w.id === id);
push(`**Nest.** ${world('nest').note}`, '');
push('| | |', '|---|---|',
     `| health | ${n(N.hp, 0)}, knitting back ${n(N.regen)}/s |`,
     `| cache | ${N.cache} supply to whoever pulls it down |`,
     `| garrison | ${N.guard} at rest, +${N.guardStep} a night to a ceiling of ${N.guardMax}, chasing ${n(N.leash)} from home |`,
     `| wakes | ${N.callN} defenders when hit, at most once every ${n(N.callGap)}s |`,
     `| sends | its difficulty's number, ×${n(N.ramp)} every night |`,
     `| spite | ${n(N.spite)} — how much harder the survivors come once one of them is dead |`, '');
push(`**Salvage Pile.** ${world('salvage').note}`, '');
push('| | |', '|---|---|',
     `| piles | ${S.nearN} near, ${S.farN} far |`,
     `| worth | ${S.amt} near, ${n(S.amt * S.farK, 0)} far (×${n(S.farK)}) |`,
     `| on the map | ${n(S.nearN * S.amt + S.farN * S.amt * S.farK, 0)} in piles, ` +
     `plus ${Object.keys(R.diff).map(d => R.diff[d].nests * N.cache + ' on ' + R.diff[d].label.toLowerCase()).join(' / ')} in caches |`, '');

push('### Difficulty', '');
push('| | starting supply | nests | each sends | base health | shambler / runner / brute |',
     '|---|---|---|---|---|---|');
for (const d in R.diff) {
  const D = R.diff[d];
  push(`| **${D.label}** | ${D.supply} | ${D.nests} | ${D.send} | ${D.hp} | ` +
       `${Math.round(D.mix.shambler * 100)}% / ${Math.round(D.mix.runner * 100)}% / ${Math.round(D.mix.brute * 100)}% |`);
}
push('',
     'The first night is every living nest\'s send added together — ' +
     Object.keys(R.diff).map(d => R.diff[d].nests * R.diff[d].send + ' on ' + R.diff[d].label.toLowerCase()).join(', ') +
     '. Pulling one down is a permanent cut to every night after it.', '');

const md = L.join('\n');
if (process.argv.includes('--print')) console.log(md);
else {
  const f = path.join(ROOT, 'ROSTER.md');
  fs.writeFileSync(f, md);
  console.log('wrote ' + f + ' (' + md.split('\n').length + ' lines)');
}
process.exit(0);
